In [1]:
# Procedural code

def simple_interest(p, r, t):
    return(p*r*t/100)

def compound_interest(p, r, t):
    return(p*pow(1+(r/100), t))

p = 100

compound_interest(p, 7, 10)

196.71513572895665

In [5]:
# OOPs code

class loan():
    def __init__(self):
        self.p = 100
    def compound_interest(self, r, t):
        return(self.p*pow(1+(r/100), t))
    
a = loan()
b = loan()
# a = dict()
# a = list()
a.compound_interest(7, 10)

196.71513572895665

In [6]:
a = int(10)
print(type(a))

c = list()
c.append(10)

<class 'int'>


## Classes

A class is a kind of data type, just like a string, integer or list. When we create an object of that data type, we call it an instance of a class.

Each class has a separate environment (no collision on function names)

In Python, everything is an object – everything is an instance of some class. 

In [7]:
sample = list()  # c = Coordinate(3, 4)
sample2 = [1, 2, 3]   # zero = Coordinate(0,0)
sample.append(sample2)  # c.distance(zero)

In [8]:
list.append(sample, sample2)

In [17]:
Coordinate.distance(c, zero)

5.0

In [18]:
Coordinate.__init__(c, 3, 4) # the reason for self

In [13]:
print(sample)

[[1, 2, 3], [1, 2, 3]]


In [14]:
class Coordinate():
    
    this_is_global = 100 # all instances of the class share this variable
    
    def __init__(self, abc, y): # different instances will have diff values
        self.x = abc
        self.y = y
        
    def distance(self, other):
        x_diff_sq = (self.x-other.x) ** 2
        y_diff_sq = (self.y-other.y) ** 2
        return (x_diff_sq + y_diff_sq) ** 0.5
    
    def __str__(self):
        return("("+str(self.x)+", "+str(self.y)+")")

In [15]:
c = Coordinate(3, 4)
print(c)

(3, 4)


In [16]:
zero = Coordinate(0,0)
print(c.distance(zero))

5.0


In [17]:
print(Coordinate.distance(c, zero))

5.0


In [19]:
print(isinstance(zero, Coordinate))

True


In [20]:
zero.this_is_global = 5

In [21]:
print(Coordinate.this_is_global)
print(zero.this_is_global)
print(c.this_is_global)

100
5
100


## Numpy


In [22]:
'''

#include <cmath>

using namespace std; 

int main()
{ int a;
cout<<"Hello";
cin>>a;
}


'''

'\n\n#include <cmath>\n\nusing namespace std; \n\nint main()\n{ int a;\ncout<<"Hello";\ncin>>a;\n}\n\n\n'

In [23]:
# from numpy import *
# __version__

In [24]:
import numpy as np
np.__version__

'1.18.1'

In [25]:
np.__version__

'1.18.1'

In [26]:
# Mention tab completion

In [27]:
?print

In [28]:
?np.__version__

In [29]:
test = np.array([1,2,3,4,5])
test2 = np.array([[1,2],[3,4]])

print(type(test), type(test2), test.shape, test2.shape)

<class 'numpy.ndarray'> <class 'numpy.ndarray'> (5,) (2, 2)


In [30]:
abc = np.array([1, 2, 3, 4], dtype='float32')
abc[0] = 100
print(abc)

[100.   2.   3.   4.]


In [31]:
sample = [1, 2, 3] + [4, 5, 6]
sample = np.array(sample)

In [32]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
test = [1, 2, 3, 4, 5]
print(test * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [37]:
print(test*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [38]:
print(test + 4*test)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [39]:
test3 = np.array([1,2,3,4,5], dtype=complex)

In [40]:
print("test3 =", test3)

print('test2 dtype =', test2.dtype)
# a = int(input())
test2 = test2.astype(np.uint8)

print('test2 dtype =', test2.dtype)

test3 = [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
test2 dtype = int32
test2 dtype = uint8


In [41]:
print('test3', test3)
# array[start:stop:skip]
print('test3[::2]', test3[::2])
print('test3[1::2]', test3[1::2])

test3 [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
test3[::2] [1.+0.j 3.+0.j 5.+0.j]
test3[1::2] [2.+0.j 4.+0.j]


In [42]:
print('test2', test2, sep="\n")
print('test2[1,1]', test2[1,1])
print('test2[1,:]', test2[1,:])
print('test2[:,1]', test2[:,1])

test2
[[1 2]
 [3 4]]
test2[1,1] 4
test2[1,:] [3 4]
test2[:,1] [2 4]


In [43]:
row_indices = [1, 2, 3]
print(test3[row_indices])

[2.+0.j 3.+0.j 4.+0.j]


In [44]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

print(A)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [45]:
x = np.ones((3, 5), dtype=float)

print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)

x ndim:  2
x shape: (3, 5)
x size:  15


In [46]:
x.dtype

dtype('float64')

In [47]:
y = x #changes to y is reflected in x

y[0, :] = 0

print(x)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
x = np.ones((3, 5), dtype=float)

y = x.copy()

y[0, :] = 0

print(x)
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [49]:
x.reshape((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
x = x.reshape((5,3))

print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [52]:
# Speed test - bear in mind that list comprehensions are vectorised

def custom_dot(A, B):
  
  C = [[0 for i in range(len(B[0]))] for j in range(len(A))]
  
  for i in range(len(A)):
    for j in range(len(B[0])):
      C[i][j] = sum(A[i,:] * B[:,j])
  
  return C
    
%time using_numpy = np.dot(A,A)
%time raw_python = custom_dot(A,A)

Wall time: 0 ns
Wall time: 0 ns


In [53]:
big_array = np.random.rand(1000000) #million
%timeit sum(big_array)
%timeit np.sum(big_array)

438 ms ± 46.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.22 ms ± 348 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [54]:
%timeit min(big_array)
%timeit np.min(big_array)

297 ms ± 27.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
952 µs ± 65.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [56]:
M = np.random.random((3, 4))
print(M)

M.min(axis=0)

[[0.68001671 0.50278385 0.9717586  0.23997244]
 [0.33493335 0.54005729 0.48667442 0.44248693]
 [0.96404569 0.56814554 0.47319868 0.61432407]]


array([0.33493335, 0.50278385, 0.47319868, 0.23997244])

In [57]:
M.max(axis=1)

array([0.9717586 , 0.54005729, 0.96404569])

In [58]:
M.min()

0.2399724422320899

In [59]:
# Broadcasting - see ppt

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [60]:
a + 5

array([5, 6, 7])

In [61]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [63]:
# Sort
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [64]:
i = np.argsort(x) #index of the sorted elements
print(i)

[1 0 3 2 4]


In [65]:
np.argmax(x), np.argmin(x)

(4, 1)

In [66]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [67]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [68]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [79]:
# argmax and argmin

a1 = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])

a1

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [81]:
np.argmax(a1)

5

In [73]:
np.argmax(a,axis=0)

array([1, 1, 1, 1], dtype=int64)

In [74]:
np.argmax(a,axis=1)

array([3, 1, 1], dtype=int64)

In [75]:
np.argmin(a)

0

In [76]:
np.argmin(a,axis=0)

array([0, 0, 2, 2], dtype=int64)

In [77]:
np.argmin(a,axis=1)

array([0, 2, 2], dtype=int64)

## That's it folks